version: "3.9"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "gzUDhXmzaxqoeoYFvgJqZcmEZSZLmLGV"  
      MYSQL_DATABASE: "railway"
    ports:
      - "3307:3306"  
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "6868:8080"  
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
