version: '3'

services:
  app_turismo:
    container_name: "sbcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://agencia_bd:3306/agencia_turismo?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    volumes:
      - ./src/main/resources/publico/uploads:/app/publico/uploads    
    restart: always
    depends_on:
      - agencia_bd

  agencia_bd:
    container_name: "agencia_db"
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: agencia_turismo
      MONGO_URL: ${MONGO_URL}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: agencia_bd
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - agencia_bd
    restart: always
    

volumes:
    mysql-data:
        
       