version: "3.9"

services:
  java_app:
    container_name: java_app
    image: julidrz-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "agencia_turismo"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: java_db
      MYSQL_ROOT_PASSWORD: root
