version: "3.9"

services:
  java_app:
    container_name: java_app
    image: julidrz-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: java_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - phpmyadmin_data:/var/lib/phpmyadmin

volumes:
  phpmyadmin_data:
